services:
  bullmq-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bullmq-test
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm start
    restart: unless-stopped
  bullmq-test-redis:
    platform: linux/x86_64
    image: redis:7
    container_name: bullmq-test-redis
volumes:
  node_modules:
